
CREATE DATABASE IF NOT EXISTS kogito;
USE kogito;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  fase INT NOT NULL DEFAULT 0,
  pontuacao INT NOT NULL DEFAULT 0,
  perguntas_index INT NOT NULL DEFAULT 0,
);
